blank_issues_enabled: false
contact_links:
  - name: Community support and questions
    url: https://github.com/martinpaljak/GlobalPlatformPro/discussions
    about: Please ask "How do I ...?" type questions in discussion forum.
